Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    
    config.vm.network:private_network, ip: "192.168.56.103"
    config.vm.hostname  = 'app'
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 5000, host: 5000
  
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
    end
    
    config.vm.provision "shell" do |shell|
      shell.path = "app.sh"
    end
  end