Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    
    config.vm.network:private_network, ip: "192.168.56.101"
    config.vm.hostname  = 'docker'
    config.vm.network "forwarded_port", guest: 4243, host: 4243
  
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
    end
    
    config.vm.provision "shell" do |shell|
      shell.path = "docker.sh"
    end
  end